from __base__ import *  # ~~~ automatically generated by __autoinject__.py ~~~

import tensorflow as tf


def __mean_squared_error(ypred: tf.Tensor, y: tf.Tensor):
    n = len(ypred)
    return sum((ypred - y) ** 2) / n


LOSS_FUNCTIONS = {
    "MSE": __mean_squared_error,
}
