"""
** BE CAREFUL WHEN RUNNING THIS FILE **

automatically injects import base to all files in python
"""

import os

blacklist = [".\\__autoinject__.py", ".\\__base__.py"]
remove = False  # if remove is False, it means we want to ADD it

for path, dnames, fnames in os.walk("."):
    print("~", path, dnames, fnames)
    for fname in fnames:
        if fname.split(".")[-1] == "py" and os.path.join(path, fname) not in blacklist:
            print(os.path.join(path, fname))
            with open(os.path.join(path, fname), "r+") as fbo:
                fdt = fbo.readlines()

                if fdt[0].count("from __base__ import *") != 1 and not remove:
                    # meaning the file does not have its first line as this, and needs to be added
                    fdt.insert(0, "from __base__ import *  # ~~~ automatically generated by __autoinject__.py ~~~ \n")
                    fbo.seek(0)
                    fbo.writelines(fdt)
                elif fdt[0].count("from __base__ import *") == 1 and remove:
                    # meaning the file does have this as its first line, and needs to be removed
                    fbo.truncate(0)
                    fbo.seek(0)
                    fbo.writelines(fdt[1:])
