from __base__ import *  # ~~~ automatically generated by __autoinject__.py ~~~

import sys
import numpy as np
np.set_printoptions(threshold=3)  # np.inf

from PySide6.QtWidgets import QApplication

import main_window


"""
Library Import:

PySide6 - GUI
Numpy - Basic data operation / Simple models
Tensorflow - AI & ML models / Complex models
Matplotlib - Data visualization
Missingno - Missing Data visualization
Pandas - Large dataset management
"""

def main():
    app = QApplication(sys.argv)
    app.setApplicationName("GraphicalAI-II")
    a_font = app.font()
    a_font.setPointSize(9)  # using PointSize to prevent automatically change the text (in this case, too small)
    app.setFont(a_font)

    win = main_window.MainWindow("GraphicalAI", "v0.18.0-alpha1")

    win.show()
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()
else:
    main()
